version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory:  ~/ffc-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install libboost-math-dev graphviz
            sudo pip install cffi flake8 pydocstyle pytest pygraphviz coverage coveralls --upgrade
      - run:
          name: Install FEniCS dependencies
          command: |
            pip install git+https://bitbucket.org/fenics-project/fiat.git --user
            pip install git+https://bitbucket.org/fenics-project/ufl.git --user
            pip install git+https://bitbucket.org/fenics-project/dijitso.git --user
      - run:
          name: Install FFC
          command: pip install -e . --user
      - run:
          name: Run flake8 tests
          command: python -m flake8 ffc/ test/
      - run:
          name: Run pydocstyle tests
          command: python -m pydocstyle ffc/
      - run:
          name: Run unit tests
          command: |
            export PATH=$PATH:$HOME/.local/bin
            coverage run --source ffc -m pytest -s test/
            coveralls
