version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/ffcx-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install --no-install-recommends graphviz libgraphviz-dev
            sudo pip install cffi 'coverage<5' flake8 pydocstyle pytest pytest-cov pytest-xdist pygraphviz coveralls --upgrade
      - run:
          name: Install FEniCS dependencies
          command: |
            pip install git+https://github.com/FEniCS/fiat.git --user
            pip install git+https://github.com/FEniCS/ufl.git --user
      - run:
          name: Install FFCX
          command: pip install . --user -v
      - run:
          name: Run flake8 tests
          command: python -m flake8 ffcx/ test/
      - run:
          name: Run pydocstyle tests
          command: python -m pydocstyle .
      - run:
          name: Run unit tests
          command: |
            export PATH=$PATH:$HOME/.local/bin
            python -m pytest --cov=ffcx/ -n 4 -v test/
            coveralls
      - run:
          name: Run demos
          command: |
            ffcx demo/*.ufl
