version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory:  ~/ffc-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install --no-install-recommends graphviz libgraphviz-dev
            sudo pip install cffi flake8 pydocstyle pytest pytest-cov pytest-xdist pygraphviz coveralls --upgrade
      - run:
          name: Install FEniCS dependencies
          command: |
            pip install git+https://github.com/FEniCS/fiat.git --user
            pip install git+https://github.com/FEniCS/ufl.git --user
      - run:
          name: Install FFC
          command: pip install . --user -v
      - run:
          name: Run flake8 tests
          command: python -m flake8 ffc/ test/
      - run:
          name: Run pydocstyle tests
          command: python -m pydocstyle .
      - run:
          name: Run unit tests
          command: |
            export PATH=$PATH:$HOME/.local/bin
            coverage run --source ffc -m pytest --cov -n 4 -v test/
            coveralls
      - run:
          name: Rerun tests (check caching)
          command: |
            export PATH=$PATH:$HOME/.local/bin
            python3 -m pytest -v test/
